name: Deploy to S3

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: './'

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Sync assets (long cache)
      run: |
        aws s3 sync ./ s3://${{ secrets.S3_BUCKET }} \
          --exclude "*.html" \
          --cache-control "public, max-age=31536000, immutable"
    
    - name: Sync HTML (no cache)
      run: |
        aws s3 sync ./ s3://$AWS_S3_BUCKET \
          --exclude "*" \
          --include "*.html" \
          --cache-control "no-cache, must-revalidate"